# Generated by Django 6.0.3 on 2026-03-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_receivers(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    User = apps.get_model('accounts', 'User')

    for message in ChatMessage.objects.filter(receiver__isnull=True).select_related('sender'):
        participants = message.room_name.split('_')
        if len(participants) != 2 or message.sender.username not in participants:
            continue

        other_username = participants[1] if participants[0] == message.sender.username else participants[0]
        try:
            receiver = User.objects.get(username=other_username)
        except User.DoesNotExist:
            continue

        message.receiver = receiver
        message.save(update_fields=['receiver'])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_image_alter_chatmessage_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_receivers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
