# Generated by Django 6.0.3 on 2026-04-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_update_chat_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='is_blocked',
        ),
    ]
